### ISSUE TITLE
basePath causes incorrect URL's

### ISSUE THREAD

**Issue by rubensworks** [csarven/mayktso#5]
Configuring the `basePath` to something like `/notifications` causes URL's like `http://linkedsoftwaredependencies.org/notifications//` and `http://linkedsoftwaredependencies.org/notifications//ce8f6020-3b98-11e7-a05e-c374a10ca702` to be formed in responses (note the `//`).

**Comment by csarven** [comment]
Can you try:
```
  "basePath" : "/notifications",
  "inboxPath": "inbox/",
  "annotationPath": "annotation/",
```

and something like:
```
ProxyPass /notifications/ https://localhost:3000/
ProxyPassReverse /notifications/ https://localhost:3000/
``

**Comment by rubensworks** [comment]
Fixed by setting up nginx config to something like:
```
  location /notifications/ {
     proxy_pass http://127.0.0.1:3001/;
     proxy_set_header Host $http_host;
     expires 1d;
   }
```
